package day2;

import java.util.stream.Stream;

public class Day2 {

    public static void main(String[] args) {
        System.out.println("PART 1");
        day2_1();

        System.out.println();

        System.out.println("PART 2");
        day2_2();
    }

    private static void day2_1() {
        String input = getInput();
        String[] rounds = input.split("\n");

        int total = Stream.of(rounds)
                .map(round -> calculateValue(round.charAt(0), round.charAt(2))).reduce(Integer::sum).get();
        System.out.println(total);
    }

    private static void day2_2() {
        String input = getInput();
        String[] rounds = input.split("\n");

        int total = Stream.of(rounds)
                .map(round -> calculateValue2(round.charAt(0), round.charAt(2))).reduce(Integer::sum).get();
        System.out.println(total);
    }

    private static int calculateValue2(char p1, char result) {
        int total = 0;
        if (p1 == 'A') {
            switch (result) {
                case 'X' -> total += 3;
                case 'Y' -> total += 4;
                case 'Z' -> total += 8;
            }
        } else if (p1 == 'B') {
            switch (result) {
                case 'X' -> total += 1;
                case 'Y' -> total += 5;
                case 'Z' -> total += 9;
            }
        } else {
            switch (result) {
                case 'X' -> total += 2;
                case 'Y' -> total += 6;
                case 'Z' -> total += 7;
            }
        }
        return total;
    }

    private static int calculateValue(char p1, char p2) {
        int total = 0;
        if (p2 == 'X') {
            total += 1;
            switch (p1) {
                case 'A' -> total += 3;
                case 'C' -> total += 6;
            }
        } else if (p2 == 'Y') {
            total += 2;
            switch (p1) {
                case 'A' -> total += 6;
                case 'B' -> total += 3;
            }
        } else {
            total += 3;
            switch (p1) {
                case 'B' -> total += 6;
                case 'C' -> total += 3;
            }
        }
        return total;
    }

    private static String getInputExample() {
        return "A Y\n" +
                "B X\n" +
                "C Z";
    }

    private static String getInput() {
        return "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "B X\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y";
    }
}
